import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import {
  readVideos,
  addSceneToVideo,
  addStandaloneScene,
  type VideoScene,
  type VideosData,
} from "./videos";

const REMOTION_ROOT = path.resolve(process.cwd(), "remotion");
const GENERATED_DIR = path.join(REMOTION_ROOT, "src", "generated");
const ROOT_TSX = path.join(REMOTION_ROOT, "src", "Root.tsx");
const MANIFEST_PATH = path.join(GENERATED_DIR, "manifest.json");
const REGISTRY_PATH = path.join(GENERATED_DIR, "_registry.ts");

const IMPORTS_START = "/* ANIMOTION_IMPORTS_START */";
const IMPORTS_END = "/* ANIMOTION_IMPORTS_END */";
const COMPOSITIONS_START = "{/* ANIMOTION_COMPOSITIONS_START */}";
const COMPOSITIONS_END = "{/* ANIMOTION_COMPOSITIONS_END */}";

interface ManifestEntry {
  name: string;
  file: string;
  duration: number;
  fps: number;
  createdAt: string;
}

interface Manifest {
  scenes: ManifestEntry[];
}

function ensureGeneratedDir() {
  if (!fs.existsSync(GENERATED_DIR)) {
    fs.mkdirSync(GENERATED_DIR, { recursive: true });
  }
}

function readManifest(): Manifest {
  if (!fs.existsSync(MANIFEST_PATH)) {
    return { scenes: [] };
  }
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
}

function writeManifest(manifest: Manifest) {
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
}

export function writeScene(
  sceneName: string,
  code: string,
  durationFrames: number,
  fps: number,
  options?: { videoId?: string; description?: string }
): { scenePath: string } {
  ensureGeneratedDir();

  const fileName = `${sceneName}.tsx`;
  const scenePath = path.join(GENERATED_DIR, fileName);

  // Write the scene file
  fs.writeFileSync(scenePath, code);

  // Update manifest (keeps backward compat)
  const manifest = readManifest();
  const existingIdx = manifest.scenes.findIndex((s) => s.name === sceneName);
  const entry: ManifestEntry = {
    name: sceneName,
    file: fileName,
    duration: durationFrames,
    fps,
    createdAt: new Date().toISOString(),
  };

  if (existingIdx >= 0) {
    manifest.scenes[existingIdx] = entry;
  } else {
    manifest.scenes.push(entry);
  }
  writeManifest(manifest);

  // Track in videos.json
  const videoScene: VideoScene = {
    name: sceneName,
    file: fileName,
    description: options?.description || "",
    duration: durationFrames,
    fps,
    createdAt: new Date().toISOString(),
  };

  if (options?.videoId) {
    addSceneToVideo(options.videoId, videoScene);
  } else {
    addStandaloneScene(videoScene);
  }

  // Update Root.tsx with video-aware folders
  const videosData = readVideos();
  updateRootTsx(manifest, videosData);

  // Update registry for @remotion/player dynamic imports
  updateRegistry(manifest);

  return { scenePath };
}

function updateRegistry(manifest: Manifest) {
  const lines = [
    "// Auto-generated by Animotion — do not edit manually",
    ...manifest.scenes.map(
      (s) => `export { ${s.name} } from "./${s.name}";`
    ),
    "",
  ];
  fs.writeFileSync(REGISTRY_PATH, lines.join("\n"));
}

function updateRootTsx(manifest: Manifest, videosData: VideosData) {
  let rootContent = fs.readFileSync(ROOT_TSX, "utf-8");

  // Inject markers if they don't exist yet
  if (!rootContent.includes(IMPORTS_START)) {
    rootContent = rootContent.replace(
      /export const RemotionRoot/,
      `${IMPORTS_START}\n${IMPORTS_END}\n\nexport const RemotionRoot`
    );
  }

  if (!rootContent.includes(COMPOSITIONS_START)) {
    rootContent = rootContent.replace(
      /(\s*)<\/>/,
      `\n      ${COMPOSITIONS_START}\n      ${COMPOSITIONS_END}\n$1</>`
    );

    if (!rootContent.includes("Folder")) {
      rootContent = rootContent.replace(
        'import { Composition } from "remotion";',
        'import { Composition, Folder } from "remotion";'
      );
    }
  }

  // Extract existing composition IDs from hand-coded section (before ANIMOTION markers)
  const handCodedSection = rootContent.split(COMPOSITIONS_START)[0];
  const existingIds = new Set(
    [...handCodedSection.matchAll(/id="([^"]+)"/g)].map((m) => m[1])
  );

  // Filter manifest scenes to exclude those that collide with hand-coded compositions
  const allScenes = manifest.scenes.filter(
    (s) => !existingIds.has(s.name)
  );

  // Build sets of scenes that belong to videos
  const videoSceneNames = new Set<string>();
  for (const video of videosData.videos) {
    for (const scene of video.scenes) {
      videoSceneNames.add(scene.name);
    }
  }

  // Standalone = in filtered manifest but not in any video
  const standaloneScenes = allScenes.filter(
    (s) => !videoSceneNames.has(s.name)
  );

  // Generate import block (all scenes, flat)
  const imports = allScenes
    .map((s) => `import { ${s.name} } from "./generated/${s.name}";`)
    .join("\n");

  // Generate composition block with group folders
  const compositionLines: string[] = [];

  // Video folders
  for (const video of videosData.videos) {
    const videoScenes = video.scenes.filter((vs) =>
      allScenes.some((ms) => ms.name === vs.name)
    );
    if (videoScenes.length === 0) continue;

    compositionLines.push(`<Folder name="${video.name}">`);
    for (const vs of videoScenes) {
      const ms = allScenes.find((s) => s.name === vs.name)!;
      compositionLines.push(
        `          <Composition`,
        `            id="${ms.name}"`,
        `            component={${ms.name}}`,
        `            durationInFrames={${ms.duration}}`,
        `            fps={${ms.fps}}`,
        `            width={1920}`,
        `            height={1080}`,
        `          />`
      );
    }
    compositionLines.push(`        </Folder>`);
  }

  // Standalone scenes (in "Generated" folder if any)
  if (standaloneScenes.length > 0) {
    compositionLines.push(`<Folder name="Generated">`);
    for (const s of standaloneScenes) {
      compositionLines.push(
        `          <Composition`,
        `            id="${s.name}"`,
        `            component={${s.name}}`,
        `            durationInFrames={${s.duration}}`,
        `            fps={${s.fps}}`,
        `            width={1920}`,
        `            height={1080}`,
        `          />`
      );
    }
    compositionLines.push(`        </Folder>`);
  }

  const compositionsBlock = compositionLines.length > 0
    ? compositionLines.join("\n        ")
    : "";

  // Replace between markers
  const importsRegex = new RegExp(
    `${escapeRegex(IMPORTS_START)}[\\s\\S]*?${escapeRegex(IMPORTS_END)}`
  );
  rootContent = rootContent.replace(
    importsRegex,
    `${IMPORTS_START}\n${imports}\n${IMPORTS_END}`
  );

  const compositionsRegex = new RegExp(
    `${escapeRegex(COMPOSITIONS_START)}[\\s\\S]*?${escapeRegex(COMPOSITIONS_END)}`
  );
  rootContent = rootContent.replace(
    compositionsRegex,
    `${COMPOSITIONS_START}\n      ${compositionsBlock}\n      ${COMPOSITIONS_END}`
  );

  fs.writeFileSync(ROOT_TSX, rootContent);
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\\/]/g, "\\$&");
}

export function validateTypeScript(): { success: boolean; errors: string } {
  try {
    execSync("npx tsc --noEmit 2>&1", {
      cwd: REMOTION_ROOT,
      encoding: "utf-8",
      timeout: 30000,
    });
    return { success: true, errors: "" };
  } catch (error: unknown) {
    const execError = error as { stdout?: string; stderr?: string };
    return {
      success: false,
      errors: execError.stdout || execError.stderr || "Unknown TypeScript error",
    };
  }
}
